version: '3'

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.1
    ports:
      - "8080:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - SKIP_DEMO_DATA=true
    volumes:
      - ./geoserver/data/:/opt/geoserver_data/
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s
